### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by zachlhb** [jitamin/jitamin#100]
下载后运行报错啊：Internal Error: Automatic Action Not Found: \Hiject\Action\TaskAssignColorCategory

**Comment by lianguan** [comment]
请更新到最新的jitamin试试。看你报错携带的namespace还是Hiject.

**Comment by zachlhb** [comment]
还是不行的，我已经把原来的文件全删了，重新下的jitamin部署的，还是报这个错

**Comment by lianguan** [comment]
我在本地开发环境和jitamin.com上都试过，暂时未能复现你提到的问题。你能不能上jitamin.com上按你的操作步骤执行一下，看看问题能不能复现。

**Comment by zachlhb** [comment]
从hiject升级到jitamin数据库要换么？
