### ISSUE TITLE
建议：创建任务的时候，能否直接上传截图？而不会等任务创建完成后，再去添加截图？

### ISSUE THREAD

**Issue by harry0703** [jitamin/jitamin#103]
创建任务的时候，能否直接上传截图？而不会等任务创建完成后，再去添加截图？
感觉这样会更方便些

另外，是否可以在任务描述文本框支持html代码？

**Comment by lianguan** [comment]
这是一个操作简便与功能的平衡问题。目前来看大多数的任务都不需要添加截图。个人觉得不应该为了极少数的任务需求，而让每个任务在创建的时候都出现上次截图。
