### ISSUE TITLE
数据库怎么升级啊

### ISSUE THREAD

**Issue by zachlhb** [jitamin/jitamin#104]
问下从hiject升级，数据库怎么升级啊？
![2017-01-04 15 05 09](https://cloud.githubusercontent.com/assets/6459106/21634105/3bd28f56-d21a-11e6-9907-7544a2132711.png)

**Comment by lianguan** [comment]
从0.2版本之后使用phinx进行数据库迁移维护。早期版本升级步骤可能有点复杂：
建设原来使用的库名是hiject。新建一个库，比如jitamin
1、执行migrate
2、查看jitamin库里的migrations
![image](https://cloud.githubusercontent.com/assets/15666864/21634249/b1a90ce8-d290-11e6-944e-f527fee41b28.png)
3、将这个表结构及收据导入到hiject库中，然后删除最后4条记录。
4、将config.php中的库切换到hiject库
5、执行migrate即可

**Comment by zachlhb** [comment]
哎，好麻烦，我重新搭建个jutamin，把东西自己转过来，辛亏数据还不多
