### ISSUE TITLE
css中的logo图片路径好像有错误，导致404

### ISSUE THREAD

**Issue by harry0703** [jitamin/jitamin#111]
background:url(/assets/img/logo.png)【404】
是不是应该改成？
background:url(/public/assets/img/logo.png)【正常】

**Comment by lianguan** [comment]
jitamin的推荐安装模式是webroot应该是指向到public。所以/assets/img/logo.png是对的。

**Comment by harry0703** [comment]
谢谢
root切换到了public，正常的
这个系统做的这是非常棒

**Comment by harry0703** [comment]
如果可以切换编辑器就好了，目前的默认是Markdown
感觉还是html的编辑器更好用，可以上传图片，附件，一次性搞定
现在还是要先创建任务，再添加截图和附件
