### ISSUE TITLE
建议：用户首页设定

### ISSUE THREAD

**Issue by harry0703** [jitamin/jitamin#140]
因为大多数开发人员，一个时期，只在一个项目中
如果可以设定 /dashboard 页面为 项目的看板页面，就很方便
用户一登录进来，直接就是 任务看板 界面，而无需再次去点击一下任务，才能进入 

目前的操作流程是：
我的 -> 我的项目 -> 项目名称 -> 进入看板
期望可以设定：
我的 -> 进入看板

管理员可以直接设定某个 用户组 或者 用户 的首页显示内容，就更棒

**Comment by lianguan** [comment]
可以将看板设置为该项目的默认入口页。
