### ISSUE TITLE
建议：指定负责人

### ISSUE THREAD

**Issue by thirty** [jitamin/jitamin#151]
- Jitamin Version: 4.2.0
- PHP Version:
- Database Driver & Version:

### Description:
是否可以设置项目的负责人，现在只能是项目“创建者”默认为负责人。

### Steps To Reproduce:

**Comment by lianguan** [comment]
![image](https://cloud.githubusercontent.com/assets/15666864/21838170/8a61fba6-d80b-11e6-8b87-90e68b6adc0a.png)
设置项目管理员不能满足要求么？现在的`负责人`可理解为 `创建人`，跟项目权限无关。

**Comment by thirty** [comment]
虽然可行，但还是有歧义。或者建议项目“负责人”索性就改为创建者。

**Comment by lianguan** [comment]
@thirty 

0.4.3已修改为 项目创建者 了。
