### ISSUE TITLE
Internal Error: Unable to write to the log file.

### ISSUE THREAD

**Issue by tiacruz** [jitamin/jitamin#172]
- Jitamin Version: dev
- PHP Version: 7.0.4
- Database Driver & Version: mysql

### Description:

Internal Error: Unable to write to the log file.

### Steps To Reproduce:

**Comment by lianguan** [comment]
You can also try to give permissions to storage

chmod -R 777 storage/

**Comment by tiacruz** [comment]
thanks. Resolve 👍
