### ISSUE TITLE
无法启动Jitamin，提示为 Internal Error: SQL error: SQLSTATE[HY000]: General error: 1 no such table: settings

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#173]
- Jitamin Version: 直接下载的github的zip包 master e8b7baec9e1812f39422397d12aa27893e3f2f9c
- PHP Version: 5.6.28
- Database Driver & Version: MySql

### Description:
我是Windows7的64位系统，装的是XAMPP V5.6.28。

### Steps To Reproduce:

按照你的文档里面的说明，我额外下载了Composer，也安装好了，而且XAMPP的控制面板我也退出后重新运行，并启动了Apache和Mysql的两个服务。

把你的git的master文件夹解压缩，放到D:\xampp\htdocs\jitamin 下面，然后在这个下面的命令行里面，依次运行了几个命令，也都提示正常。
这些命令包括：
```
安装依赖包命令
创建数据表
安装初始数据
```
这些命令都是在命令行里面打的，都没有出现问题，依赖包我看到也都正确下载来安装了，我还配置了文件 D:\xampp\htdocs\jitamin\config\config.php
里面主要设置了一个我新建的数据库名字，我在http://localhost:8082/phpmyadmin 下面，新建了一个名字为jitamin的数据库，utf8的类型，也都没有问题。（默认是root的用户名，没有密码，端口是3306）

现在我在浏览器里面输入地址： [http://localhost:8082/jitamin/public/](http://localhost:8082/jitamin/public/)
出来的提示内容是：
Internal Error: SQL error: SQLSTATE[HY000]: General error: 1 no such table: settings

请问我该怎么办？

如果直接访问http://localhost:8082/jitamin 的话，我就是得到一个文件的列表。

**Comment by asmwarrior** [comment]
哦，明白了，在那个配置里面，需要设置：

```
    // Available db drivers are "mysql", "sqlite" and "postgres"
    'db_driver' => 'mysql',
```

现在网站可以跑起来了。

**Comment by dexcomman** [comment]
求助   遇到相同问题了   可是跟你一样只是修改了sqlite到mysql却没法运行啊  还是internal 错误
