### ISSUE TITLE
移动或者重设任务将改变任务开始和截止时间，但是时间错一天

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#174]
- Jitamin Version: 直接下载的github的zip包 master e8b7baec9e1812f39422397d12aa27893e3f2f9c
- PHP Version: 5.6.28
- Database Driver & Version: MySql

### Description:
这个功能挺不错的，但是有一个bug，就是比如我把起始的日子，拉到某个月的2号，结果鼠标一放掉，这个日期会向左边移动一下，然后变成某月的1号。言下之意，日子会向左回退一格，当拖拽结束的时候。

**Comment by asmwarrior** [comment]
我再次测试了这个问题，感觉这个问题不是经常发生，但是偶有发生，奇怪。用的Firefox浏览器，Windows7系统。

**Comment by lianguan** [comment]
已修复，在mac chrome测试没有问题。
