### ISSUE TITLE
建议你增加一些英文的说明文档

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#175]
你现在的readme.md 里面都是中文，这样不利于这个软件的推广，同时用英文也有利于更多的国外友人参与进来一起开发

**Comment by lianguan** [comment]
非常感谢，你如果有兴趣可以做这件事，欢迎发送PR

**Comment by asmwarrior** [comment]
我的想法是：你把这个readme搞成英文的吧，我觉得你弄一个中文和一个英文的安装手册，可能维护不是很方便，直接弄一个英文的，可以慢慢补充进去，这个倒是不错。而且我觉得一般人其实对于安装来说。中文或者英文应该都看得懂。你要同意，我觉得我在改英文上可以出点力气，哈哈。

**Comment by lianguan** [comment]
可以

**Comment by asmwarrior** [comment]
花了点时间修改了一下，你看一下，我已经发起了PR，但是不怎么会用github，有问题及时反馈，呵呵。我打算在一个大概几十人的团队用你这个软件来管理，所以希望这个软件一直都保持进步，呵呵。

**Comment by lianguan** [comment]
看到了，感谢。里面还是很多chinglish 😄

**Comment by asmwarrior** [comment]
呵呵，是的，有chinglish很正常，我英语也不咋地，我觉得可以慢慢改进。
