### ISSUE TITLE
在设置任务“结束日期”的时候，弹出来的日期显示控件的上下翻月按钮颜色和背景一致

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#177]
- Jitamin Version: 直接下载的github的zip包 master e8b7baec9e1812f39422397d12aa27893e3f2f9c
- PHP Version: 5.6.28
- Database Driver & Version: MySql

### Description:
截图如下

![2017-01-24 08 40 15](https://cloud.githubusercontent.com/assets/561818/22237890/7cecb220-e249-11e6-9ab8-8d7290fad5a2.png)

### Steps To Reproduce:
添加一个Task的时候，在进行“结束日期”选择的时候，发现上下翻页按钮和背景颜色一致。见上面的截图。

**Comment by asmwarrior** [comment]
另外还有一个问题是：对于一个任务，你的开始时间是带这日期和小时分钟的，结束日期是不带这个的，是不是考虑统一一下？

**Comment by asmwarrior** [comment]
> 另外还有一个问题是：对于一个任务，你的开始时间是带这日期和小时分钟的，结束日期是不带小时和分钟的，是不是考虑统一一下？

测试了一个官方的Kanboard的demo，貌似他们也是这样的，估计是故意这么设置的。

**Comment by dexcomman** [comment]
我觉得如果能加上结束时间的小时分钟更好

**Comment by asmwarrior** [comment]
请问这个问题在哪个commit里面解决了？？？
