### ISSUE TITLE
项目列表里面的标题栏：“泳道”是什么意思？干什么用？

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#178]
- Jitamin Version: 直接下载的github的zip包 master e8b7baec9e1812f39422397d12aa27893e3f2f9c
- PHP Version: 5.6.28
- Database Driver & Version: MySql

### Description:
请问项目列表里面的标题栏：“泳道”是什么意思？干什么用？谢谢。

**Comment by lianguan** [comment]
泳道可根据自身项目的情况灵活应用。比如可以作为milestone，sprint或版本发布version1,version2....
