### ISSUE TITLE
项目列表里面，一行显示中文，一行显示英文

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#179]
- Jitamin Version: 直接下载的github的zip包 master e8b7baec9e1812f39422397d12aa27893e3f2f9c
- PHP Version: 5.6.28
- Database Driver & Version: MySql

### Description:
我估计是在项目语言或者哪个地方设置过语言选项，导致现在显示的这个项目列表里面，“栏目”这一栏，一行是中文，一行是英文，见下面的截图：

http://i63.tinypic.com/zk2uqw.png

### Steps To Reproduce:
具体操作步骤我有点忘记了，反正是从昨天到今天创建了两个项目，然后设置了一些东西，就变成这样了。

**Comment by lianguan** [comment]
栏目属于项目的一部分。创建项目的时候，系统给该项目自动创建的栏目是跟随系统语言的。尽管如此，你还可以在项目设置里把栏目修改为你想要的。

**Comment by asmwarrior** [comment]
谢谢回复，你的意思是：是不是可以在栏目里面的此处，直接修改这些字符串？
看我截图的箭头处的内容，言下之意，这些地方的内容是写死的，一旦用了中文，就显示中文，一开始如果用了英文，就一直是英文的了？

http://i66.tinypic.com/uy3yv.png

谢谢！

**Comment by lianguan** [comment]
看不到图片，请直接上传图片到github，谢谢。

**Comment by asmwarrior** [comment]
![2017-01-24 09 56 42](https://cloud.githubusercontent.com/assets/561818/22231083/371126aa-e21c-11e6-897f-a5bcb247dd42.png)
图片上传好了，请看一下。

**Comment by lianguan** [comment]
直接在`设置`，将英文`Backlog`等修改为对应中文即可。这是项目属性，不是系统语言，可以根据每个项目的实际情况任意修改为自己想要的栏目。
