### ISSUE TITLE
当设置的电子邮箱地址已经被别的用户占用的时候，是否考虑给一个提示，现在是什么提示都没有

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#181]
- Jitamin Version: 直接下载的github的zip包 master e8b7baec9e1812f39422397d12aa27893e3f2f9c
- PHP Version: 5.6.28
- Database Driver & Version: MySql

### Description:
用admin登陆，然后进入用户管理，选择admin用户，然后是更改电子邮件，点击最下面的保存。
发现保存后，电子邮件地址还是  admin@admin.com

**Comment by asmwarrior** [comment]
我知道是什么原因了，因为输入的邮箱地址，被别的用户占用了，所以修改不成功，但是我的建议是在点击保存按钮之后，应该给一个提示，否则大家一团雾水，呵呵。

**Comment by lianguan** [comment]
Fixed
