### ISSUE TITLE
编辑自定义角色的时候提示错误

### ISSUE THREAD

**Issue by asmwarrior** [jitamin/jitamin#183]
- Jitamin Version: 直接下载的github的zip包 master e8b7baec9e1812f39422397d12aa27893e3f2f9c
- PHP Version: 5.6.28
- Database Driver & Version: MySql

### Description:

添加项目角色的时候，程序提示错误，截屏如下
![2017-01-24 13 39 11](https://cloud.githubusercontent.com/assets/561818/22235472/cf21a4ec-e23a-11e6-81ed-655f27dacf10.png)

### Steps To Reproduce:
进入某个项目的设置，再右侧选择自定义角色，然后添加一个角色，添加好之后，点击菜单里面的编辑该角色，则提示错误。

错误信息如下：

![2017-01-24 13 44 41](https://cloud.githubusercontent.com/assets/561818/22235553/3aa87fec-e23b-11e6-9757-7fdd84c55422.png)

**Comment by lianguan** [comment]
已修复
