### ISSUE TITLE
请问简体中文怎么设置

### ISSUE THREAD

**Issue by jinjiang2009** [jitamin/jitamin#190]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:

**Comment by lianguan** [comment]
![image](https://cloud.githubusercontent.com/assets/15666864/22772492/f222f46a-eed7-11e6-9a06-32ed42386d36.png)

**Comment by jinjiang2009** [comment]
谢谢
