### ISSUE TITLE
PostgreSQL连接不正常

### ISSUE THREAD

**Issue by denghualiang** [jitamin/jitamin#191]
- Jitamin Version: 0.4.6
- PHP Version: 5.6.10
- Database Driver & Version: PostgreSql

### Description:
PHP错误信息，看起来像是无法正确获得postgresql的hostname。
( ! ) Notice: Undefined index: postgres in /Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php on line 72
Call Stack
#	Time	Memory	Function	Location
1	0.0014	247056	{main}( )	../index.php:0
2	0.0017	254768	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/autoload.php' )	../index.php:13
3	0.0204	872936	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php' )	../autoload.php:34

( ! ) Notice: Undefined index: postgres in /Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php on line 75
Call Stack
#	Time	Memory	Function	Location
1	0.0014	247056	{main}( )	../index.php:0
2	0.0017	254768	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/autoload.php' )	../index.php:13
3	0.0204	872936	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php' )	../autoload.php:34

( ! ) Notice: Undefined index: postgres in /Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php on line 78
Call Stack
#	Time	Memory	Function	Location
1	0.0014	247056	{main}( )	../index.php:0
2	0.0017	254768	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/autoload.php' )	../index.php:13
3	0.0204	872936	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php' )	../autoload.php:34

( ! ) Notice: Undefined index: postgres in /Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php on line 81
Call Stack
#	Time	Memory	Function	Location
1	0.0014	247056	{main}( )	../index.php:0
2	0.0017	254768	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/autoload.php' )	../index.php:13
3	0.0204	872936	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php' )	../autoload.php:34

( ! ) Notice: Undefined index: postgres in /Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php on line 84
Call Stack
#	Time	Memory	Function	Location
1	0.0014	247056	{main}( )	../index.php:0
2	0.0017	254768	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/autoload.php' )	../index.php:13
3	0.0204	872936	require( '/Applications/MAMP/htdocs/jitamin/bootstrap/bootstrap.php' )	../autoload.php:34

( ! ) Fatal error: Uncaught exception 'LogicException' with message 'This configuration parameter is missing: "hostname"' in /Applications/MAMP/htdocs/jitamin/vendor/fguillot/picodb/lib/PicoDb/Driver/Base.php on line 125
( ! ) LogicException: This configuration parameter is missing: "hostname" in /Applications/MAMP/htdocs/jitamin/vendor/fguillot/picodb/lib/PicoDb/Driver/Base.php on line 125
Call Stack
#	Time	Memory	Function	Location
1	0.0014	247056	{main}( )	../index.php:0
2	0.0264	826032	require_once( '/Applications/MAMP/htdocs/jitamin/bootstrap/app.php' )	../index.php:16
3	0.0345	1100152	Pimple\Container->register( ???, ??? )	../app.php:17
4	0.0346	1100376	Jitamin\Providers\DatabaseServiceProvider->register( ??? )	../Container.php:274
5	0.0346	1100456	Jitamin\Providers\DatabaseServiceProvider->getInstance( )	../DatabaseServiceProvider.php:33
6	0.0346	1100520	Jitamin\Providers\DatabaseServiceProvider->getPostgresInstance( )	../DatabaseServiceProvider.php:59
7	0.0354	1151080	PicoDb\Database->__construct( ??? )	../DatabaseServiceProvider.php:116
8	0.0356	1158056	PicoDb\DriverFactory::getDriver( ??? )	../Database.php:61
9	0.0379	1221880	PicoDb\Driver\Base->__construct( ??? )	../DriverFactory.php:40

### Steps To Reproduce:

**Comment by lianguan** [comment]
请确认 config/config.php 相关配置是否正常。能否贴上来看看？

**Comment by denghualiang** [comment]
@lianguan 
'db_driver' => 'postgres',
'pgsql' => [
            'driver'   => 'pgsql',
            'host'     => 'localhost',
            'database' => 'project',
            'username' => 'postgres',
            'password' => '',
            'port'     => '5432',
            'charset'  => 'utf8',
        ],
创建数据结构和初始数据都是OK的，但浏览器打开首页就会报以上错误。
另外，请问Jitamin有没有官网更详细的介绍？感觉是个很不错的产品，但是能力水平有限，有些地方看不太懂，前端是用什么技术实现的？如果要修改前端大概应该怎么弄？麻烦指个方向。

**Comment by lianguan** [comment]
应该是配置文件的数组写错了，改成这样的试试。
```php
'pgsql' => [
```
改为：

```php
'postgres' => [
```
