### ISSUE TITLE
安装后运行起来地址栏变成这样子了

### ISSUE THREAD

**Issue by Shiloh520** [jitamin/jitamin#198]
http://jitamin.dev/Users/yixiao/.composer/vendor/laravel/valet/?controller=Auth/AuthController&action=login

**Comment by lianguan** [comment]
webserver的相关web root没有配置好。

**Comment by Shiloh520** [comment]
我用的是vatel，检查了web root的地址的确是指向`Users/yixiao/.composer/vendor/laravel/valet/`。

但是如果我修改它，其他的项目就会`404 not found`。

我试着在项目的根目录下直接`php artisan serve`，提示说

> serve is not defined

这意味着这不是用laravel搭建的？我只能用自己配置的ngnix运行？
