### ISSUE TITLE
Internal Error: SQL error: SQLSTATE[42S02]: Base table or view not found

### ISSUE THREAD

**Issue by dexcomman** [jitamin/jitamin#199]
- Jitamin Version: #.#.#  
   0.4.7 dev
- PHP Version: 5.6.3
- Database Driver & Version:
  bitnami wamp一键包 （mysql），win7 x64

### Description:

Internal Error: SQL error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jitamin.settings' doesn't exist
   
### Steps To Reproduce:
**https://github.com/jitamin/jitamin/issues/173**
  与上一个Internal Error 的哥们一样，我一开始也遇到了settings表不存在的错误，但是我修改config里面数据库连接后发现仍然存在上述错误，与帖子里老兄几乎相同的步骤，我直接用zip解压到E盘里没有用Git。
似乎是数据库没有创建好表，经过搜索发现没有相关解决办法，特此求助

**Comment by lianguan** [comment]
切换数据库记得要执行相关的migration操作。

**Comment by dexcomman** [comment]
之前用mysql崩溃比较多    换了postgresql，请问应该用怎样迁移，还有那个http代理环境变量设置了后显示
`这个位于公司、组织或学校内网中的网站使用的网址与某个外部网站的网址相同 ERR_ICANN_NAME_COLLISION`
并报了以上的错，请问该如何解决呢
