### ISSUE TITLE
第一泳道的显示问题

### ISSUE THREAD

**Issue by AlexYuan** [jitamin/jitamin#208]
- Jitamin Version: 0.4.7-dev 
- PHP Version: 5.6
- Database Driver & Version:

### Description:
泳道名称和分类的上下位置有误，举例：

![image](https://cloud.githubusercontent.com/assets/1269376/25601965/877d9c38-2f22-11e7-8e48-adfa9c9ce3bf.png)

### Steps To Reproduce:

**Comment by lianguan** [comment]
图片貌似没上传成功哦

**Comment by asmwarrior** [comment]
应该为jitamin是基于官方的Kanboard进行的改进，我测试了一下官方的Kanboard，结果也是如你的截图所示，所以我觉得这个问题应该报告给kanboard。

**Comment by asmwarrior** [comment]
查了一下，kanboard官方就有讨论，而且这个issue还是处于open状态，见：[First swimline row under the column headers one · Issue #2575 · kanboard/kanboard](https://github.com/kanboard/kanboard/issues/2575)
