### ISSUE TITLE
配置后访问错误

### ISSUE THREAD

**Issue by lhtdeg** [jitamin/jitamin#210]
- Jitamin Version: 当前版本
- PHP Version: 7
- Database Driver & Version: mariadb-10.1.18

部署完成后访问出现如下错误。
`Fatal error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in D:\jitamin\vendor\fguillot\picodb\lib\PicoDb\Driver\Mysql.php:86 Stack trace: #0 D:\jitamin\vendor\fguillot\picodb\lib\PicoDb\Driver\Mysql.php(49): PicoDb\Driver\Mysql->buildOptions(Array) #1 D:\jitamin\vendor\fguillot\picodb\lib\PicoDb\Driver\Base.php(129): PicoDb\Driver\Mysql->createConnection(Array) #2 D:\jitamin\vendor\fguillot\picodb\lib\PicoDb\DriverFactory.php(38): PicoDb\Driver\Base->__construct(Array) #3 D:\jitamin\vendor\fguillot\picodb\lib\PicoDb\Database.php(61): PicoDb\DriverFactory::getDriver(Array) #4 D:\jitamin\app\Providers\DatabaseServiceProvider.php(98): PicoDb\Database->__construct(Array) #5 D:\jitamin\app\Providers\DatabaseServiceProvider.php(56): Jitamin\Providers\DatabaseServiceProvider->getMysqlInstance() #6 D:\jitamin\app\Providers\DatabaseServiceProvider.php(33): Jitamin\Providers\DatabaseServiceProvider->getInstance() #7 D:\jitamin\vendor\pimple\pimple\src\Pimple\Container.php(274): Jitamin\Providers\DatabaseServi in D:\jitamin\vendor\fguillot\picodb\lib\PicoDb\Driver\Mysql.php on line 86`

**Comment by lianguan** [comment]
mysql pdo打开了么？
