### ISSUE TITLE
[feature]新建任务时，可以有地方附上图片或文档之类的么？

### ISSUE THREAD

**Issue by agentwx** [jitamin/jitamin#213]
- Jitamin Version: 0.4.7
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:

**Comment by lianguan** [comment]
目前的设计可以在新建任务完成后，进入任务详情页添加附件和图片，毕竟这个并不是高频的操作。

**Comment by agentwx** [comment]
刚发现，确实这样也够用，感谢~
