### ISSUE TITLE
大哥，请问container生产脚本是在哪里注册的，能不能说一下项目的结构？

### ISSUE THREAD

**Issue by yaoxiang879** [jitamin/jitamin#217]
class Application extends Base
{
    /**
     * Execute middleware and controller.
     */
    public function execute()
    {
        if ($this->runningInConsole()) {
            $this->container['dispatcher']->dispatch('app.bootstrap', new Event());
            $this->container['cli']->run();

            return;
        }

        $this->container['router']->dispatch();

        if ($this->container['router']->getController() === 'Api') {
            echo $this->container['api']->execute();

            return;
        }

        try {
            $this->executeMiddleware();

            if (!$this->response->isResponseAlreadySent()) {
                $this->executeController();
            }
        } catch (PageNotFoundException $e) {
            $controllerObject = new AppController($this->container);
            $controllerObject->notFound($e->hasLayout());
        } catch (AccessForbiddenException $e) {
            $controllerObject = new AppController($this->container);
            $controllerObject->accessForbidden($e->hasLayout(), $e->getMessage());
        }
    }
........
}

$this->container['router']->getController() ‘router生产脚本是在哪定义的？？？？？？
请大神指点一下？？？？？？’

**Comment by yaoxiang879** [comment]
我想根据这个软件制作一个自己的小网站，但是代码看不懂，请指点，谢谢

**Comment by lianguan** [comment]
![image](https://user-images.githubusercontent.com/15666864/28663407-de5877ba-72ef-11e7-9592-3bccebb40e3a.png)

router请看routes/目录下的那些文件。
