### ISSUE TITLE
项目中某些变量是怎么生成的，生成机制是什么？

### ISSUE THREAD

**Issue by yaoxiang879** [jitamin/jitamin#219]
很多类中会出现 $this -> helper, $this -> db, $this -> sessionStorage -> scope,,,,,,,,,,,,,这些变量我找遍项目也没找到，它们是在哪定义的？或者是怎么生成的？
![617h u1 c w01mf5tfs tb](https://user-images.githubusercontent.com/18574459/28753119-a14d9b2e-7561-11e7-859b-5279ad05df9c.png)
如上图中，$this ->response 变量是在哪生成的？是不是通过服务容器生成的？
请指教！

**Comment by lianguan** [comment]
建议先看看Pimple，然后再看jitamin的其中一个入口文件bootstrap/app.php。以sessionStorage为例：bootstrap/app.php -> 在bootstrap/config/app.php找到Jitamin\Providers\SessionServiceProvider::class -> app/Providers/SessionServiceProvider.php就能看到 sessionStorage 这个变量了。
