### ISSUE TITLE
请问这是laravel的哪个版本？

### ISSUE THREAD

**Issue by yaoxiang879** [jitamin/jitamin#220]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:

**Comment by lianguan** [comment]
用的不是laravel框架哦。

**Comment by yaoxiang879** [comment]
我的天，你用的是什么框架？？？？？？？？？？急急急急急急急急急！！！！！！！！！！！！！！！收到请回复，谢谢谢谢谢谢！！！！！！！！！！！！！！！！！！！！！

**Comment by yaoxiang879** [comment]
肯定是在逗我
