### ISSUE TITLE
创建一个Model类文件，引入其它Model基类，运行时出现找不到引入的Model类的错误

### ISSUE THREAD

**Issue by yaoxiang879** [jitamin/jitamin#224]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:
![1](https://user-images.githubusercontent.com/18574459/28917849-a4479fd0-7879-11e7-90b1-d414e86f7248.png)

### Description:
如上图，创建RecentProModel类，引入Model基类，类的provider中已经声明，运行到$this->currentProModel时出现标题中的错误！

### Steps To Reproduce:

**Comment by easyYao** [comment]
@suriski

**Comment by suriski** [comment]
我在models 创建了一个 "TaskOsModel" 类 ，

```
namespace Jitamin\Model;

use Jitamin\Foundation\Database\Model;

/**
 * Category model.
 */
class TaskOsModel extends Model
{
          ...
}

```
在ClassServiceProvider已经声明了TaskOsModel ，
但是在controlelr 中 无法Internal Error: Identifier "TaskOsModel" is not defined.

@easyYao

**Comment by suriski** [comment]
@easyYao 您好，已经解决了，谢谢您，是因为$this->taskOsModel 大小写错误了。
