### ISSUE TITLE
建议: 日期格式问题

### ISSUE THREAD

**Issue by pyzheng** [jitamin/jitamin#228]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
现在的日期格式是:MM/DD/YYYY  是否可以自定义日期格式，比如:YYYY-MM-DD，谢谢

### Steps To Reproduce:

**Comment by lianguan** [comment]
这个在后台可配置的。
后台->系统设置->国际化设置->日期格式
