### ISSUE TITLE
甘特图问题

### ISSUE THREAD

**Issue by pyzheng** [jitamin/jitamin#229]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
甘特图右边无法默认现实当前日期的位置

### Steps To Reproduce:

**Comment by lianguan** [comment]
没太明白您的意思？能再详细描述一下么？

**Comment by pyzheng** [comment]
我的意思是  甘特图默认显示当前任务。 我修改了源码，解决了点击左边的任务，自动移动到相应的日期。
不过没关系了，后面我自己看看怎么实现默认显示当前的任务和位置
