### ISSUE TITLE
“项目成员”功能项报错

### ISSUE THREAD

**Issue by jiahm** [jitamin/jitamin#239]
- Jitamin Version: 0.4.7-dev
- PHP Version:7.0.25
- Database Driver & Version:mysql 5.7.18-log

### Description:
系统显示
Internal Error: SQL error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'group_id' at row 1

### Steps To Reproduce:
1、点击管理；
2、项目列表中选择一个项目；
3、右上角“菜单”选择“设置”；
4、右边列表中选择“项目成员”；
5、在“项目团队”中的“团队名称”输入任意值；
6、点击回车；
7、显示Internal Error: SQL error: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'group_id' at row 1

**Comment by lianguan** [comment]
@jiahm 已修复。

**Comment by jiahm** [comment]
thank you
