### ISSUE TITLE
Master分支，移动位置功能不生效

### ISSUE THREAD

**Issue by timmyzhang** [jitamin/jitamin#241]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Description:
我的->我的任务->点击具体任务详情->右侧移动位置按钮->保存后，任务状态并没有更改。

### Steps To Reproduce:

**Comment by lianguan** [comment]
已修正

**Comment by timmyzhang** [comment]
已验证，没问题了，多谢。
