### ISSUE TITLE
怎么设置上传附件大小

### ISSUE THREAD

**Issue by beango** [jitamin/jitamin#242]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:

**Comment by lianguan** [comment]
jitamin本身没有限制，取决于你的web server和php的post size等设置情况，jitamin取其最小值。

**Comment by beango** [comment]
设置了PHP，提示上传成功了，但是找不到附件
![j1](https://user-images.githubusercontent.com/1934559/34398324-f3b884aa-ebb8-11e7-9075-8d7ee4c04841.png)
![j2](https://user-images.githubusercontent.com/1934559/34398327-f704948c-ebb8-11e7-8fd7-32741dee686c.png)

**Comment by lianguan** [comment]
![image](https://user-images.githubusercontent.com/15666864/34398765-71809b72-ebbc-11e7-9436-879b65048968.png)
我刚试了，没有复现你说的这个问题。
