### ISSUE TITLE
laravel分支无法使用，依赖lock管理仓库已删除

### ISSUE THREAD

**Issue by dark-wind** [jitamin/jitamin#294]
- Jitamin Version: 0.4.6 (2017-01-26)
- PHP Version: 7.0.20-2
- Database Driver & Version: mysql5.7

### Description:
laravel分支无法使用，composer install 失败
很多个仓库都找不到了

### Steps To Reproduce:

**Comment by lianguan** [comment]
请用最新的版本，谢谢。
