### ISSUE TITLE
fguillot/picodb is not found,the package is no-use

### ISSUE THREAD

**Issue by fire-ball-wang** [jitamin/jitamin#295]
- Jitamin Version: #.#.#
- PHP Version:
- Database Driver & Version:

### Steps To Reproduce:

**Comment by caiyongtian** [comment]
Jitamin Version: master
PHP Version: 7.2
Database Driver: mysql & Version:5.6
Description: git repo fguillot/picodb is delete,so what repo can replace it ?
Steps To Reproduce:the shell command is composer install --no-dev

**Comment by fire-ball-wang** [comment]
my composer switch the ``` https://packagist.laravel-china.org ```, and it's ok
