### ISSUE TITLE
不要改名儿可不可以嘞？

### ISSUE THREAD

**Issue by palmtale** [jitamin/jitamin#59]
Lianguan哥，刚发现你把 Hiject 改成jitamin, 很是不解。因为这给追随你这项目的人们带来困惑：比如哪天我在github里一搜hijiect，找不着啦。我是本身watch的，才是可以看到本项目。你看你那里有209个stars呢

另外，给你竖个大姆指，之前不知道上哪给你这点赞。你这不是在重造轮子，有着“很少能找到的我需要的项目管理软件”的样子：有甘特图，燃尽图等Agile，看板等需要的东西（不是清楚 是否是Kanborad原来就带）。在市很有名的像Taiga只有看板的样子，Worktile我在用，但没有各种图什么的。  而且是基于Laravel，我最熟的Php framework,所以很容易我就setup起一个pmi.glad.so.   我docker弄地。不过发现 php 7.1.0不可以，因为7.1又去掉一些原来的built方法。真闹，也不知道这算是php的锅还是kanboard的锅。   

我如果有时间可以contribute你这项目一下，哈哈，现在怕自己会不负责任。

**Comment by lianguan** [comment]
感谢支持，第一次也是最后一次改名 😄
