### ISSUE TITLE
0.2.4版本Windows下部署,无法正常登陆.

### ISSUE THREAD

**Issue by thirty** [jitamin/jitamin#86]
使用默认用户名密码登陆后自动跳回登陆界面，往复循环。

**Comment by lianguan** [comment]
0.2.4的登录页模板有bug，请尝试修改resources/views/auth/index.php

将
```php
<form method="post" action="<?= $this->url->href('AuthController', 'check') ?>">
```

修改为
```php
<form method="post" action="<?= $this->url->href('Auth/AuthController', 'check') ?>">
```

**Comment by thirty** [comment]
好的，我将继续关注。谢谢

**Comment by thirty** [comment]
另外您将navi.php内的提醒和增加项目注释掉了，从0.2.3 到0.2.5版本一直这样。是否是有意的？

**Comment by lianguan** [comment]
移到左侧的sidebar了。

**Comment by thirty** [comment]
如果不打开注释的话，无法增加项目呀？
另外0.2.5版本有多个link 路径错误。
如:
Internal Error: Controller not found: \Jitamin\Controller\ProjectUserOverviewController

座等下个版本，元旦快乐。

**Comment by lianguan** [comment]
@thirty 感谢反馈，在master分支已修复。欢迎在jitamin.com多多帮忙测试。
