### ISSUE TITLE
V0.3.2 登陆后报错。

### ISSUE THREAD

**Issue by thirty** [jitamin/jitamin#97]
登陆后
Fatal error: Class 'Jitamin\Controller\Dashboard\ProjectController' not found in D:\phproot\jitamin\app\Http\Controllers\Dashboard\DashboardController.php on line 27

**Comment by lianguan** [comment]
升级后，请别忘了执行composer install

**Comment by thirty** [comment]
已解决。
好勤快的项目，升级好快！
