### ISSUE TITLE
没法初始化数据

### ISSUE THREAD

**Issue by netxdiy** [jitamin/jitamin#98]
四. 安装数据库迁移和初始数据

创建数据表
php vendor/bin/phinx migrate
安装初始数据
php vendor/bin/phinx seed:run

这两条命令在windows上没法执行。

方便直接把sql文件上传吗

**Comment by lianguan** [comment]
我没在windows下安装过jitamin.

可以尝试 
php vendor/robmorgan/phinx/bin/phinx.bat migrate
php vendor/robmorgan/phinx/bin/phinx.bat seed:run

**Comment by netxdiy** [comment]
不成功 @lianguan ，方便把sql文件上传吗

**Comment by lianguan** [comment]
修改一下呢？

```shell
php vendor\robmorgan\phinx\bin\phinx.bat migrate
php vendor\robmorgan\phinx\bin\phinx.bat seed:run
```

不建议直接导入sql。jitamin靠phinx维护数据迁移及升级。

**Comment by netxdiy** [comment]
测试了，没成功。那用linux部署下吧

**Comment by lianguan** [comment]
建议把错误日志贴上来，也许其他同学能解决呢。

**Comment by lianguan** [comment]
用这个吧。

```shell
vendor\robmorgan\phinx\bin\phinx.bat migrate
vendor\robmorgan\phinx\bin\phinx.bat seed:run
```

**Comment by lianguan** [comment]
![image](https://cloud.githubusercontent.com/assets/15666864/21600596/d9ce33d8-d1b9-11e6-9e7a-a2951571a2db.png)

**Comment by thirty** [comment]
我在windows上部署成功了。一定要这样。
d:\phproot\jitamin\vendor\bin\phinx.bat migrate   
d:\phproot\jitamin\vendor\bin\phinx.bat seed:run

写全路径。

**Comment by netxdiy** [comment]
好的

**Comment by thirty** [comment]
我给的例子是在  D:\phproot\jitamin> 位置执行的。
您可以尝试一下。

**Comment by netxdiy** [comment]
@lianguan 
vendor\robmorgan\phinx\bin\phinx.bat migrate
vendor\robmorgan\phinx\bin\phinx.bat seed:run
这个可以成功。
